replicaCount: 2

image:
  repository: europe-southwest1-docker.pkg.dev/custom-manifest-435411-u7/swapi-people-sorter/swapi-people-sorter
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 5000
  nodePort: 30001

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  host: swapi-people-sorter.local
  path: /

resources: {}
