name: CI/CD Pipeline with GKE and Helm

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t europe-southwest1-docker.pkg.dev/custom-manifest-435411-u7/swapi-people-sorter/swapi-people-sorter:latest ./app

      - name: Set up Google Cloud authentication
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: custom-manifest-435411-u7
          export_default_credentials: true

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker europe-southwest1-docker.pkg.dev

      - name: Push Docker Image to GCP Registry
        run: |
          docker push europe-southwest1-docker.pkg.dev/custom-manifest-435411-u7/swapi-people-sorter/swapi-people-sorter:latest

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install kubectl

      - name: Get GKE Credentials
        run: |
          gcloud container clusters get-credentials cluster-1 --zone us-central1-c --project custom-manifest-435411-u7

      - name: Deploy to GKE with Helm
        run: helm upgrade --install swapi-people-sorter .
